-- MySQL Script generated by MySQL Workbench
-- Tue Dec 26 18:00:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd` DEFAULT CHARACTER SET utf8 ;
USE `bd` ;

-- -----------------------------------------------------
-- Table `bd`.`asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`asistencia` ;

CREATE TABLE IF NOT EXISTS `bd`.`asistencia` (
  `idAsistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idAsistencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`departamento` ;

CREATE TABLE IF NOT EXISTS `bd`.`departamento` (
  `idDepartamento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`barrio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`barrio` ;

CREATE TABLE IF NOT EXISTS `bd`.`barrio` (
  `idBarrio` INT(11) NOT NULL AUTO_INCREMENT,
  `idDepartamento` INT(11) NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idBarrio`),
  INDEX `fk_Barrio_Departamento_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_Barrio_Departamento`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `bd`.`departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 364
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`tipo_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`tipo_servicio` ;

CREATE TABLE IF NOT EXISTS `bd`.`tipo_servicio` (
  `idTipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`categoria` ;

CREATE TABLE IF NOT EXISTS `bd`.`categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL DEFAULT '1',
  `Tipo_Servicio_idTipo` INT(11) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_Categoria_Tipo_Servicio1_idx` (`Tipo_Servicio_idTipo` ASC),
  CONSTRAINT `fk_Categoria_Tipo_Servicio1`
    FOREIGN KEY (`Tipo_Servicio_idTipo`)
    REFERENCES `bd`.`tipo_servicio` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`genero` ;

CREATE TABLE IF NOT EXISTS `bd`.`genero` (
  `idGenero` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`persona` ;

CREATE TABLE IF NOT EXISTS `bd`.`persona` (
  `idPersona` INT(11) NOT NULL AUTO_INCREMENT,
  `idBarrio` INT(11) NOT NULL,
  `idGenero` INT(11) NOT NULL,
  `dni` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `apellido` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `direccion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `numero` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `correo` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Barrio1_idx` (`idBarrio` ASC),
  INDEX `fk_Persona_Genero1_idx` (`idGenero` ASC),
  CONSTRAINT `fk_Persona_Barrio1`
    FOREIGN KEY (`idBarrio`)
    REFERENCES `bd`.`barrio` (`idBarrio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Genero1`
    FOREIGN KEY (`idGenero`)
    REFERENCES `bd`.`genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`servicio` ;

CREATE TABLE IF NOT EXISTS `bd`.`servicio` (
  `idServicio` INT(11) NOT NULL AUTO_INCREMENT,
  `idCategoria` INT(11) NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `duracion` INT(11) NOT NULL,
  `precio` INT(11) NOT NULL,
  `detalle` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `activo` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idServicio`),
  INDEX `fk_Servicio_Categoria1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_Servicio_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bd`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`detalle_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`detalle_servicio` ;

CREATE TABLE IF NOT EXISTS `bd`.`detalle_servicio` (
  `idDetalle` INT(11) NOT NULL AUTO_INCREMENT,
  `idPersona` INT(11) NOT NULL,
  `idAsistencia` INT(11) NOT NULL,
  `idServicio` INT(11) NOT NULL,
  `hora` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `precio` INT(11) NOT NULL,
  `descuento` INT NOT NULL,
  `pagado` INT NOT NULL,
  `observacion` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `fk_Detalle_Servicio_Persona1_idx` (`idPersona` ASC),
  INDEX `fk_Detalle_Servicio_Asistencia1_idx` (`idAsistencia` ASC),
  INDEX `fk_detalle_servicio_servicio1_idx` (`idServicio` ASC),
  CONSTRAINT `fk_Detalle_Servicio_Asistencia1`
    FOREIGN KEY (`idAsistencia`)
    REFERENCES `bd`.`asistencia` (`idAsistencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Servicio_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `bd`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_servicio_servicio1`
    FOREIGN KEY (`idServicio`)
    REFERENCES `bd`.`servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`sucursal` ;

CREATE TABLE IF NOT EXISTS `bd`.`sucursal` (
  `idSucursal` INT(11) NOT NULL AUTO_INCREMENT,
  `idBarrio` INT(11) NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `numero` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `direccion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `codigoPostal` INT(11) NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursal_Barrio1_idx` (`idBarrio` ASC),
  CONSTRAINT `fk_Sucursal_Barrio1`
    FOREIGN KEY (`idBarrio`)
    REFERENCES `bd`.`barrio` (`idBarrio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`trabajador` ;

CREATE TABLE IF NOT EXISTS `bd`.`trabajador` (
  `idTrabajador` INT(11) NOT NULL AUTO_INCREMENT,
  `idSucursal` INT(11) NOT NULL,
  `idPersona` INT(11) NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idTrabajador`),
  INDEX `fk_Trabajador_Persona1_idx` (`idPersona` ASC),
  INDEX `fk_Trabajador_Sucursal1_idx` (`idSucursal` ASC),
  CONSTRAINT `fk_Trabajador_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `bd`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajador_Sucursal1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `bd`.`sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`detalle_trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`detalle_trabajador` ;

CREATE TABLE IF NOT EXISTS `bd`.`detalle_trabajador` (
  `idDetalle` INT(11) NOT NULL AUTO_INCREMENT,
  `idServicio` INT(11) NOT NULL,
  `idTrabajador` INT(11) NOT NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `fk_Detalle_Trabajador_Trabajador1_idx` (`idTrabajador` ASC),
  INDEX `fk_Detalle_Trabajador_Detalle_Servicio1_idx` (`idServicio` ASC),
  CONSTRAINT `fk_Detalle_Trabajador_Detalle_Servicio1`
    FOREIGN KEY (`idServicio`)
    REFERENCES `bd`.`detalle_servicio` (`idDetalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Trabajador_Trabajador1`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `bd`.`trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`especialidad` ;

CREATE TABLE IF NOT EXISTS `bd`.`especialidad` (
  `idEspecialidad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`huella`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`huella` ;

CREATE TABLE IF NOT EXISTS `bd`.`huella` (
  `idHuella` INT(11) NOT NULL AUTO_INCREMENT,
  `huella` BLOB NULL DEFAULT NULL,
  `llave` INT(32) NOT NULL,
  PRIMARY KEY (`idHuella`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `bd`.`tipo_usuario` (
  `idTipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bd`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `idPersona` INT(11) NOT NULL,
  `idTipo` INT(11) NOT NULL,
  `contrasena` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Persona1_idx` (`idPersona` ASC),
  INDEX `fk_Usuario_Tipo_Usuario1_idx` (`idTipo` ASC),
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `bd`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Tipo_Usuario1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `bd`.`tipo_usuario` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd`.`detalle_TrabEsp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`detalle_TrabEsp` ;

CREATE TABLE IF NOT EXISTS `bd`.`detalle_TrabEsp` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `idTrabajador` INT(11) NOT NULL,
  `idEspecialidad` INT(11) NOT NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `fk_detalle_TrabEsp_trabajador1_idx` (`idTrabajador` ASC),
  INDEX `fk_detalle_TrabEsp_especialidad1_idx` (`idEspecialidad` ASC),
  CONSTRAINT `fk_detalle_TrabEsp_trabajador1`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `bd`.`trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_TrabEsp_especialidad1`
    FOREIGN KEY (`idEspecialidad`)
    REFERENCES `bd`.`especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`cliente` ;

CREATE TABLE IF NOT EXISTS `bd`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT(11) NOT NULL,
  `activo` INT(1) NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_cliente_persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `bd`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`detalle_ClienteHuella`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`detalle_ClienteHuella` ;

CREATE TABLE IF NOT EXISTS `bd`.`detalle_ClienteHuella` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `idHuella` INT(11) NOT NULL,
  `idCliente` INT NOT NULL,
  `estado` INT(1) NOT NULL DEFAULT 0,
  `llave` INT(32) NOT NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `fk_detalle_PersonaHuella_huella1_idx` (`idHuella` ASC),
  INDEX `fk_detalle_PersonaHuella_cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_detalle_PersonaHuella_huella1`
    FOREIGN KEY (`idHuella`)
    REFERENCES `bd`.`huella` (`idHuella`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_PersonaHuella_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`tipo_cuponera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`tipo_cuponera` ;

CREATE TABLE IF NOT EXISTS `bd`.`tipo_cuponera` (
  `idTipo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`cuponera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`cuponera` ;

CREATE TABLE IF NOT EXISTS `bd`.`cuponera` (
  `idCuponera` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idTipo` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estado` INT(1) NOT NULL,
  `ven` DATETIME NOT NULL,
  `valor` INT NOT NULL,
  `descuento` INT NOT NULL,
  `pagado` INT NOT NULL,
  PRIMARY KEY (`idCuponera`),
  INDEX `fk_Cuponera_cliente1_idx` (`idCliente` ASC),
  INDEX `fk_cuponera_tipo_cuponera1_idx` (`idTipo` ASC),
  CONSTRAINT `fk_Cuponera_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuponera_tipo_cuponera1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `bd`.`tipo_cuponera` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`sesion` ;

CREATE TABLE IF NOT EXISTS `bd`.`sesion` (
  `idSesion` INT NOT NULL,
  `idServicio` INT(11) NOT NULL,
  `idCuponera` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estado` INT(1) NOT NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `fk_Sesion_Cuponera1_idx` (`idCuponera` ASC),
  INDEX `fk_Sesion_servicio1_idx` (`idServicio` ASC),
  CONSTRAINT `fk_Sesion_Cuponera1`
    FOREIGN KEY (`idCuponera`)
    REFERENCES `bd`.`cuponera` (`idCuponera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sesion_servicio1`
    FOREIGN KEY (`idServicio`)
    REFERENCES `bd`.`servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
